# Generated by Django 3.0.7 on 2020-06-15 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ICSSA_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='highlighted',
        ),
    ]
