# Generated by Django 3.0.7 on 2020-06-15 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ICSSA_app', '0002_remove_student_highlighted'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='level',
            unique_together={('name',)},
        ),
    ]
