# Generated by Django 3.0.7 on 2020-06-16 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ICSSA_app', '0005_auto_20200616_0224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='executivetenure',
            name='members',
        ),
        migrations.RemoveField(
            model_name='pollquestion',
            name='choices',
        ),
    ]
